import type { Metadata } from 'next';
import Link from 'next/link';
import { SUB_CSS, SiteHeader, SiteFooter, CtaBand } from '@/components/SiteChrome';
import { SAMPLE_STORIES } from '@/lib/sampleStories';

const BASE = 'https://www.talepopstories.com';

export const metadata: Metadata = {
  title: 'Free sample bedtime stories to read',
  description:
    'Read complete personalised bedtime stories for kids, free, no signup. Real TalePop stories with their own illustrations. Ages 3 to 10.',
  alternates: { canonical: `${BASE}/sample-stories` },
  openGraph: {
    title: 'Free sample bedtime stories to read',
    description:
      'Complete personalised bedtime stories for children aged 3 to 10, free to read with no signup.',
    url: `${BASE}/sample-stories`,
  },
};

export default function SampleStoriesPage() {
  const schema = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'CollectionPage',
        name: 'Free sample bedtime stories',
        url: `${BASE}/sample-stories`,
        description:
          'Complete personalised bedtime stories for kids, free to read with no signup.',
        isPartOf: { '@type': 'WebSite', url: BASE, name: 'TalePop' },
      },
      {
        '@type': 'ItemList',
        itemListElement: SAMPLE_STORIES.map((s, i) => ({
          '@type': 'ListItem',
          position: i + 1,
          name: s.title,
          url: `${BASE}/sample-stories/${s.slug}`,
        })),
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: BASE },
          { '@type': 'ListItem', position: 2, name: 'Sample stories' },
        ],
      },
    ],
  };

  return (
    <>
      <style>{SUB_CSS}</style>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
      <SiteHeader />

      <div className="wrap phead">
        <p className="kick">Read before you sign up</p>
        <h1>Free sample bedtime stories you can read right now</h1>
        <p className="lede">
          Complete personalised bedtime stories, start to finish, with the illustrations that came
          with them. No signup, no email, nothing to close. Read one and you will know exactly what
          arrives at bedtime.
        </p>
      </div>

      <div className="wrap">
        <div className="grid grid-3">
          {SAMPLE_STORIES.map((s) => (
            <Link className="tp-card" href={`/sample-stories/${s.slug}`} key={s.slug}>
              <div className="tp-card-img">
                <img src={s.image} alt={s.alt} loading="lazy" decoding="async" width={1200} height={1500} />
              </div>
              <h3>{s.title}</h3>
              <p>
                {s.emoji} {s.theme} &middot; {s.age} &middot; {s.readingLevel} level
              </p>
            </Link>
          ))}
        </div>

        <div className="prose">
          <h2>These are real stories, not marketing samples</h2>
          <p>
            Each story on this page came out of TalePop the same way a subscriber&apos;s would. We
            picked a theme and a reading level, the story was written and illustrated, and then we
            filled the child&apos;s name in with a stand-in so it reads properly. Nothing was
            rewritten afterwards to sound better.
          </p>
          <p>
            That matters because &quot;personalised&quot; means very different things across this
            category. A lot of personalised children&apos;s books are one fixed story with a name
            dropped into the gaps, which is why two children get the same book. Read the{' '}
            <Link href="/sample-stories/unicorn-bedtime-story">unicorn story</Link> next to the{' '}
            <Link href="/sample-stories/dinosaur-bedtime-story">dinosaur one</Link> and you can see
            they are not the same shape with different nouns.
          </p>

          <h2>Reading level, not just age</h2>
          <p>
            The dinosaur sample is a beginner story for ages 3 to 5. It is short on purpose, with
            simple sentences and one clear moment per page. The unicorn and superhero samples are
            advanced, for ages 7 to 10, and run to a proper three-act structure with a real
            complication in the middle.
          </p>
          <p>
            When you set up a child profile you choose that level, and it changes vocabulary,
            sentence length and story complexity. It is the difference between a book your child
            can follow and one they lose interest in halfway through.
          </p>

          <h2>Where the pictures come from</h2>
          <p>
            Every illustration is generated by our own model, trained in house on our own artwork.
            We did not licence a stock library and we do not use a general purpose image generator.
            The reason is consistency: a child needs to look like the same child on page one and
            page twelve, and only a model trained for that will hold a character together across a
            whole book.
          </p>
          <p>
            <Link href="/story-ideas">Browse every story idea we can build from</Link>, or read
            about <Link href="/about">why we built TalePop</Link>.
          </p>
        </div>
      </div>

      <CtaBand
        heading="Their story will have their name in it"
        body="Pick their interests, set their reading level, and the first personalised story book is free."
      />
      <SiteFooter />
    </>
  );
}
