// Sample stories published openly so parents (and search engines) can read a real
// TalePop story before signing up.
//
// These are genuine product output: each one was generated by TalePop from a theme
// and reading level, then had its {{NAME}} placeholder filled with a stand-in name.
// The wording is not marketing copy written after the fact.

export type SampleStory = {
  slug: string;
  theme: string;
  age: string;
  name: string;
  readingLevel: string;
  wordCount: number;
  title: string;
  moral: string;
  emoji: string;
  image: string;
  alt: string;
  kw: string;
  pages: string[][];
};

export const SAMPLE_STORIES: SampleStory[] = [
  {
    "slug": "dinosaur-bedtime-story",
    "theme": "Dinosaurs",
    "age": "Ages 3 to 5",
    "name": "Zak",
    "readingLevel": "beginner",
    "wordCount": 300,
    "title": "Zak and the Little Dinosaur Behind the Rock",
    "moral": "A friendly smile can turn a scared heart into a happy one.",
    "emoji": "🦕",
    "image": "/journey/world-dino.avif",
    "alt": "A child meeting a friendly dinosaur in a personalised dinosaur bedtime story",
    "kw": "personalised dinosaur bedtime story",
    "pages": [
      [
        "Zak walked through a big valley of tall green ferns. Giant rocks stood all around him. The ground was soft and muddy. Strange sounds came from far away. Zak looked and looked at everything around him. This place was very exciting."
      ],
      [
        "Behind a big grey rock, two little eyes looked out. They blinked at Zak. A tiny green dinosaur was hiding there. It had big round eyes and a small round body. It was shaking a little. It looked so scared."
      ],
      [
        "Zak sat down on the soft ground. He held out his hand, very slowly. He did not move fast. He did not make any loud sounds. The little dinosaur took one step. Then two steps. Then it walked right up to Zak."
      ],
      [
        "The little dinosaur put its head into Zak's hand. Its skin was smooth and cool. Zak gave it a gentle pat. The little dinosaur let out a happy little sound. They were friends now. Real friends."
      ],
      [
        "Zak and the little dinosaur sat together as the sky turned pink. They watched the stars come out one by one. Zak felt warm and happy and sleepy. Being kind to someone shy is a special thing. Zak closed his eyes. And somewhere in the dark, a very big something moved slowly through the ferns."
      ]
    ]
  },
  {
    "slug": "unicorn-bedtime-story",
    "theme": "Unicorns",
    "age": "Ages 7 to 10",
    "name": "Leo",
    "readingLevel": "advanced",
    "wordCount": 700,
    "title": "Leo and the Unicorn Who Carried the Last Map",
    "moral": "Some burdens are lighter when carried together, and some paths can only be found by the one willing to walk beside the lost.",
    "emoji": "🦄",
    "image": "/journey/world-unicorn.avif",
    "alt": "A child riding a winged unicorn through the clouds in a personalised unicorn bedtime story",
    "kw": "personalised unicorn bedtime story",
    "pages": [
      [
        "The Windmere Valley had been losing its colour for three years. Not dramatically, not all at once, but in the slow, unobtrusive way that things disappear when no one is looking directly at them: the deep blue of the gentians fading to grey, the bright gold of the evening light becoming thin and wan, the mountain snowline that had always sparkled now simply white and flat, like chalk pressed against a pale sky. Leo had walked every path of the valley since he was old enough to wear boots, and he knew its colours the way you know the face of someone you love. He was the valley's youngest chronicler, keeper of the Windmere Record, a great leather-bound book in which every significant change to the valley was noted and dated, and the pattern he had recorded was deeply troubling. He was kneeling beside the faded gentians on the eastern slope, pressing a dried specimen between the pages of his record, when the unicorn appeared among the silver birches above him: enormous, utterly still, her coat not the brilliant white of stories but a deep, worn ivory, and in her dark eyes, something that looked unmistakably like exhaustion."
      ],
      [
        "Her name, she told him, was Seren, and she had been carrying the Rootmap of Windmere for four hundred years. The Rootmap was not a physical object, she explained, but a living record inscribed across her coat in ink visible only in moonlight, the original map of every ley line, every colour-source, every deep spring of light and warmth that ran beneath the valley and gave it its extraordinary life. The problem was that the map had begun to unravel. Age and isolation had frayed the inscriptions at their edges, and as each line faded from her coat, the corresponding source in the valley faded too. She had been searching for a chronicler, someone who recorded the truth of the valley carefully enough to understand it, someone she could trust to help her re-anchor the fading lines before they were lost entirely. She had been watching Leo from the birch forest for two weeks. Leo sat down on a boulder, looked at Seren's eyes, which were the deep quiet brown of autumn rivers, and felt the particular weight of being needed in a way that was larger than himself, not frightening, but enormously serious."
      ],
      [
        "That night under a full moon they worked together on the high ridge of the valley where the ley lines were strongest and the map on Seren's coat blazed with silver luminosity, intricate and precise and in places heartbreakingly incomplete. Leo spread his chronicle open on the flat rock and began to transcribe, his pen moving fast to match Seren's guidance, who read the remaining inscriptions aloud in a voice like wind through long grass. Each completed section of the map had to be anchored in the chronicle, bound by being recorded, made permanent in ink that would hold what Seren's coat could no longer sustain. Leo's hand cramped. His eyes blurred from the concentration of reading moonlit lines on a moving, breathing surface. But every time he completed a section, a corresponding piece of the valley below responded: a cluster of gentians blazed suddenly, vividly blue in the dark; a stream he'd watched run dry began to murmur again from somewhere below the ridge. He could hear the valley waking up around him, tentative and grateful as something returning from a long sleep, and he wrote faster."
      ],
      [
        "The last section of the map was the deepest one and the most damaged, a series of fine lines radiating from the valley's central spring, the source of every colour-thread in the whole network, and here the inscriptions on Seren's coat were almost gone, mere ghost-traces that Leo had to press his face very close to see at all. Seren stood absolutely still, not breathing, her patience immense and ancient. He worked with a precision that surprised even himself, recording each fragment with the care of someone who understands that small things are sometimes the load-bearing ones. When he transcribed the last line and said so aloud, the silence that followed was total, a held breath that the valley itself seemed to take. Then, from the central spring far below, a column of light rose slowly into the night sky, not white but every colour simultaneously, the deep gold of morning light and the blue of deep water and the vivid green of new leaves all braided together, and Seren made a sound that was not quite a word but was entirely clear in meaning: relief, at last, complete."
      ],
      [
        "By the time Leo climbed back down to the valley floor, the gentians were so blue they seemed to hum, and the morning light that crept over the eastern ridge was the rich particular gold he remembered from his very earliest walks, when his boots had been new and the valley had seemed inexhaustible in its beauty. Seren walked beside him to the edge of the birch forest and then stopped, and he understood without being told that this was where she would wait now, her burden shared and lightened, the map held safely in the chronicle he would carry and tend. She dipped her great horn toward him, once, which seemed to Leo to contain approximately as much as any gesture possibly could. He walked home through a valley that was, in every measurable sense, itself again, and went to bed still in his coat, too tired to do anything but pull off his boots and let the warm morning light fall across him like the softest possible hand. He slept. The compass on its chain lay cool against his chest. And in the deep middle of his rest, it began, very gently, to rotate on its own, pointing not north but toward something new it had never pointed at before."
      ]
    ]
  },
  {
    "slug": "superhero-bedtime-story",
    "theme": "Superheroes",
    "age": "Ages 7 to 10",
    "name": "Noah",
    "readingLevel": "advanced",
    "wordCount": 700,
    "title": "Noah and the Power No One Wanted",
    "moral": "The ability everyone overlooks is often the one the moment was made for.",
    "emoji": "🦸",
    "image": "/journey/world-hero.avif",
    "alt": "A child in a superhero cape in a personalised superhero bedtime story",
    "kw": "personalised superhero bedtime story",
    "pages": [
      [
        "The Meridian Academy for Exceptional Abilities was built like a tall silver ship moored in the clouds, and every student in it had a power that made people's eyes go wide. Zara could move mountains, quite literally, which took up a lot of space in the Academy's practical training field. Leo generated sound waves powerful enough to shatter stone walls with a single syllable. Even the newest students had abilities that sparked and crackled and left scorch marks. Noah had been at the Academy for three months, and his ability was that he could understand any language. Every language. Spoken ones, written ones, ancient ones, codes and signals and the particular patterns of data moving through machines, all of it arrived in his mind as clear and natural as his own mother tongue. The other students were polite about it. Their politeness had the careful, cushioned quality of people trying hard not to say what they were thinking, which was that languages seemed like a quiet sort of power for a school full of people who could redirect rivers."
      ],
      [
        "The alarm that woke the Academy at 2am was not an ordinary alarm. It was the deep resonant clang of the breach bell, a sound that had not been heard in twenty years, and it meant that something had penetrated the Academy's outer security systems and was now inside the infrastructure, not the building, but the Academy's digital nervous system: every door, every lock, every communications channel, every emergency beacon. The Academy was functionally blind and deaf. Director Chen gathered the senior students in the main hall, speaking in a controlled voice that barely concealed her urgency. The intruder was a sophisticated piece of code, she said, unlike anything the Academy's own engineers had encountered, layered and complex and apparently written in a language that predated any known programming standard. She looked around the room at her most powerful students: Zara, Leo, the others, each brilliant and capable and, in this moment, completely unable to help. Then her gaze settled on Noah, and for the first time in three months it was without polite cushioning. It was direct, and assessing, and almost hopeful."
      ],
      [
        "They plugged Noah into the diagnostic terminal with three cables connected to his silver gauntlets, and the moment the connection was live the intruder code appeared to him not as meaningless data but as language, dense and layered and old, a dialect of machine-language he had never encountered but could read the way you can understand an old relative who speaks in a slightly different way to everyone else. He worked fast, typing responses in the intruder's own dialect, conducting a negotiation inside the Academy's systems that no one else in the room could follow, the scroll of data on the screens making Zara frown and Leo shake his head in bafflement. Director Chen stood behind him, watching the screens, and Noah explained as he typed, a running commentary that got faster and more confident as he understood what the code actually was: not a weapon, not an attack, but an automated distress signal from a disabled hero-class AI, locked inside a forgotten Academy satellite, trying desperately to communicate using a protocol so old no one had remembered how to read it. Until now. His fingers flew. The breach bell fell silent."
      ],
      [
        "The satellite AI's name was Arden, and it had been alone in orbit for nineteen years, running low on power, transmitting its distress call on the old protocol every six hours without reply, cycling through hope and endurance in the particular patient way of machines that were built with something like stubbornness. When Noah's response arrived in its own language for the first time in nearly two decades, Arden's reply was immediate and, by any reasonable measure, the most grateful message Noah had ever read. He worked with Director Chen to begin the process of relinking Arden to the Academy's modern communications network, translating in real time between Arden's old dialect and the new systems, a bridge of language spanning nineteen years of silence. When the full connection was established, Arden transmitted everything it had recorded from orbit: nineteen years of data on atmospheric threats, incoming disruptions, undetected anomalies, all of it perfectly logged, all of it waiting to be read. Director Chen looked at the data pouring onto the screens and then looked at Noah with an expression that needed no translation whatsoever."
      ],
      [
        "They gave Noah a new designation the next morning, at a small ceremony in the Academy's main hall, a different title to the ones most students received, not Striker or Shieldbearer or Vanguard. Director Chen called him the Academy's first Interpreter, and explained to the assembled students why interpretation, the ability to hear what others cannot hear and understand what others cannot understand, was perhaps the rarest and most essential ability of all. Zara, who could move mountains, said quietly that she thought so too. Noah walked back to his room under a sky that the morning had turned an extraordinary pale gold, and he felt as though the uniform fit differently now, as though the cape had always been just the right length. He went to sleep as the sun cleared the clouds and his room filled with soft warm light, his gauntlets on the bedside table still faintly warm from the night's work, his breathing slow and easy and full. And just before sleep took him completely, his gauntlets pulsed once with a soft blue light, and a signal arrived from Arden, twenty thousand kilometres above, short and simple and clear: 'Something new approaching. I think you'll want to hear this.'"
      ]
    ]
  }
];

export function getStory(slug: string) {
  return SAMPLE_STORIES.find((s) => s.slug === slug);
}
